version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: docker/backend.Dockerfile
    command: sh -c "python scripts/initialize_data.py && uvicorn api.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - VECTOR_DB_HOST=vector_db
      - VECTOR_DB_PORT=6333
    depends_on:
      - vector_db

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  vector_db:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
